### ISSUE TITLE
formatierung grafik beschreibung

### ISSUE THREAD

**Issue by O-Sven** [FireDynamics/LectureComputerScience#2]
die formatierung von grafik unterschriften funktioniert nicht mehr richtig, siehe 1.2 Algorithmen

**Comment by O-Sven** [comment]
außerdem sind grafiken und tabellen nicht zentriert

**Comment by O-Sven** [comment]
grafiken wurden bisher in tabellen eingefügt mit der bildunterschrift einfach in der nächsten zeile. allerdings funktioniert das nicht mehr gut mit der neuen tabellenformatierung
der richtige weg wären figures:
```{figure} ../images/abc.png
---
height: 150px
name: directive-fig
---
Here is my figure caption!
```

oder markdown figures, die html links und markdown in der bildunterschrift erlauben:
:::{figure-md} markdown-fig
<img src="../images/fun-fish.png" alt="fishy" class="bg-primary mb-1" width="200px">

This is a caption in **Markdown**!
:::

**Comment by lu-kas** [comment]
done für 1.1.*

ich mache für die anderen neue issues...
