### ISSUE TITLE
zentrieren von grafiken und tabellen

### ISSUE THREAD

**Issue by O-Sven** [FireDynamics/LectureComputerScience#6]
grafiken und tabellen werden linksbündig angezeigt
<center> tabelle </center> würde diese wieder zentrieren

**Comment by lu-kas** [comment]
die bilder sind wieder zentral, aber eines der videos bekomme ich nicht zentriert, abschnitt 1.1.1

hast du @O-Sven eine idee?

**Comment by O-Sven** [comment]
hab ich gemacht

**Comment by O-Sven** [comment]
aufgeteilt in weitere issues
